import { baseApi } from "../base";
import { GetPartyRequest, GetPartyResponse } from "./types";

/**
 * This method is used to get all information about an individual Party. The
 * Party ID must be specified as a request parameter to get the party
 * information.
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MTM4
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} partyId - Party ID that is generated by the API once an individual party is created (createParty).
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {Array} partyDetails - Array of party includes all information of the matched party( partyId, firstName,middleInitial,lastName,domicile,socialSecurityNumber,dob,primAddress1,primAddress2,primCity,primState,primZip,primCountry,emailAddress,emailAddress2,phone,phone2,occupation,associatedPerson,empCountry,empAddress1,empAddress2,empCity,empState,empZip,currentAnnIncome,avgAnnIncome,currentHouseholdIncome,avgHouseholdIncome,householdNetworth,kycStatus,kycDate,amlStatus,amlDate,tags,notes)
 */
export default async function ({
  clientID,
  developerAPIKey,
  partyId,
}: GetPartyRequest): Promise<GetPartyResponse> {
  try {
    const payload: GetPartyRequest = {
      clientID,
      developerAPIKey,
      partyId,
    };
    return await baseApi("getParty", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
