import axios, { AxiosRequestConfig } from "axios";
import * as FormData from "form-data";
import { BASE_URL } from "../base";
import {
  UploadTradeDocumentRequest,
  UploadTradeDocumentResponse,
} from "./types";

/**
 * This method is used to upload documents to a particular trade (createTrade).
 *
 * Files uploaded cannot be larger than 100 MB.
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MjMy
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} tradeId - Trade ID that is generated by the API
 * @param {string} documentName - Title of the document
 * @param {string | Blob} file - PDF, jpg, and png files are supported
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {string} document_details - Document has been uploaded Successfully
 */
export default async function ({
  clientID,
  developerAPIKey,
  tradeId,
  documentName,
  file,
}: UploadTradeDocumentRequest): Promise<UploadTradeDocumentResponse> {
  const formData = new FormData();
  formData.append("clientID", clientID);
  formData.append("developerAPIKey", developerAPIKey);
  formData.append("tradeId", tradeId);
  formData.append("documentTitle", `documentTitle0=${documentName}`);
  formData.append("file_name", `filename0=${documentName}.pdf`);
  formData.append("userfile0", file, { filename: `${documentName}.pdf` });

  const config: AxiosRequestConfig = {
    method: "POST",
    url: BASE_URL + "uploadTradeAgreement",
    headers: { ...formData.getHeaders() },
    data: formData,
  };

  try {
    await axios(config);
    // TODO: figure out how to receive response from file upload
    return {
      statusCode: "101",
      statusDesc: "Ok",
      document_details: "Document has been uploaded Successfully",
    };
  } catch (error) {
    throw new Error(error.message);
  }
}
