import { baseApi } from "../base";
import { CcFundMovePayload, CcFundMoveResponse } from "./types";

/**
 * This method is used to get all information for an account (createAccount).
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MTM2
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} accountId - Account ID that is generated by the API once an account is created (createAccount).
 * @param {string} tradeId - Trade ID that is generated by the API once a trade is created (createTrade). A trade must be created before the 'ccFundmove' method can be performed.
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {Array} accountDetails - Array of account includes all information of the matched account
 */
export default async function ({
  clientID,
  developerAPIKey,
  accountId,
  tradeId,
}: CcFundMovePayload): Promise<CcFundMoveResponse> {
  try {
    const payload: CcFundMovePayload = {
      clientID,
      developerAPIKey,
      accountId,
      tradeId,
      createdIpAddress: "69.61.177.110",
    };
    return await baseApi("ccFundMove", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
