import { baseApi } from "../base";
import { CcFundMoveRequest, CcFundMoveResponse } from "./types";

/**
 * This method is used to get all information for an account (createAccount).
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MTM2
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} accountId - Account ID that is generated by the API once an account is created (createAccount).
 * @param {string} tradeId - Trade ID that is generated by the API once a trade is created (createTrade). A trade must be created before the 'ccFundmove' method can be performed.
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {Array} transactionDetails - Array of transaction details of the credit card number
 */
export default async function ({
  clientID,
  developerAPIKey,
  accountId,
  tradeId,
}: CcFundMoveRequest): Promise<CcFundMoveResponse> {
  try {
    const payload: CcFundMoveRequest = {
      clientID,
      developerAPIKey,
      accountId,
      tradeId,
      createdIpAddress: "69.61.177.110",
    };
    return await baseApi("POST", "ccFundMove", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
