import { baseApi } from "../base";
import { GetTradeRequest, GetTradeResponse } from "./types";

/**
 * This method is used to get all the details of all the trades for an account.
 * The Account ID is required to get the details.
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MjEw
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} accountId - Account ID generated by the API
 * @param {string} tradeId - Trade ID generated by the API
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {Array} partyDetails - Returns the party trade details as an array
 */
export default async function ({
  clientID,
  developerAPIKey,
  accountId,
  tradeId,
}: GetTradeRequest): Promise<GetTradeResponse> {
  try {
    const payload: GetTradeRequest = {
      clientID,
      developerAPIKey,
      accountId,
      tradeId,
    };
    return await baseApi("getTrade", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
