import { baseApi } from "../base";
import {
  CreateExternalAccountRequest,
  CreateExternalAccountResponse,
} from "./types";

/**
 * This method is used to add information to an Account (createAccount) for an external bank account which an ACH transfer can be initiated from. Only one external account can be created for an account. External accounts can have funds debited from them (externalFundMove) but cannot have funds sent to them.
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MjA0
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} types Is this for an Account or Issuer Account?
 * @param {string} accountId - Account ID or Issuer ID that is generated by the API when an Account(createAccount) or Issuer(createIssuer) is created.
 * @param {string} ExtAccountfullname - Account Holder Full Name or Issuer Account Holder Full Name
 * @param {string} Extnickname - Nickname for the External Account
 * @param {string} ExtRoutingnumber - External Bank Account - Routing Number
 * @param {string} ExtAccountnumber - External Bank Account - Account Number
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {string} accountId/IssuerId - Account ID / Issuer ID
 * @returns {string} ExtAccountfullname - External Account Full Name
 * @returns {string} Extnickname - External Account Nick Name
 * @returns {string} ExtRoutingnumber - External Account Bank Routing Number
 * @returns {string} ExtAccountnumber - External Account Bank Account Number
 * @returns {string} types - Type Account/Issuer
 * @returns {string} accountType - Account type Checking / Saving. By default Checking
 */
export default async function ({
  clientID,
  developerAPIKey,
  types,
  accountId,
  ExtAccountfullname,
  Extnickname,
  ExtRoutingnumber,
  ExtAccountnumber,
  accountType,
}: CreateExternalAccountRequest): Promise<CreateExternalAccountResponse> {
  try {
    const payload: CreateExternalAccountRequest = {
      clientID,
      developerAPIKey,
      types,
      accountId,
      ExtAccountfullname,
      Extnickname,
      ExtRoutingnumber,
      ExtAccountnumber,
      accountType,
    };
    return await baseApi("createExternalAccount", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
