import { baseApi } from "../base";
import { GetOfferingRequest, GetOfferingResponse } from "./types";

/**
 * This method is used to get all the details of an offering. The Offering ID
 * is required to get the information.
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MTY4
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} offeringId - Offering ID that is generated by the API when an Offering is created(createOffering).
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {Array} TradeDetails - Details of the matched offer as an array ( issuerId, offeringId, issueName, issueType, targetAmount, minAmount, maxAmount, unitPrice, totalShares, remainingShares, startDate, endDate, offeringStatus, offeringText, stampingText)
 */
export default async function ({
  clientID,
  developerAPIKey,
  offeringId,
}: GetOfferingRequest): Promise<GetOfferingResponse> {
  try {
    const payload: GetOfferingRequest = {
      clientID,
      developerAPIKey,
      offeringId,
    };
    return await baseApi("POST", "getOffering", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
